name: Laravel

on:
  push:
    branches: [ "master" ]
  

jobs:
  laravel-deployment:
    name: create-deployment-artifacts
    runs-on: self-hosted

    steps:
    - name: composer install
      run: composer install --no-dev --no-interaction --prefer-dist
