name: Laravel

on:
  push:
    branches: [ "master" ]
  

jobs:
  laravel-deployment:
    name: create-deployment-artifacts
    runs-on: self-hosted

    steps:
    - name: configure php 8
      uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: 8.0
        extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml
